USe mydatabase;
select * from costumer limit 10;

SELECT * FROM mydatabase.costumer LIMIT 10;


show databases;
-- Q1. what is the total revenue generated by males bs female costumers? 
select gender, sum(purchase_amount) as revenue
from costumer
group by gender

-- Q2. which costumers used a discount but still spend more than the average purchase amount?
select customer_id, purchase_amount 
from costumer 
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from costumer)

-- Q3. which are the top 5 products with the highest average review ratings?
select item_purchased, ROUND(AVG(review_rating), 2) as "average_product_rating"
from costumer
group by item_purchased
order by avg(review_rating) desc
limit 5;
